name: Release 
 
on: 
  workflow_dispatch: 
 
env: 
  VERSION: '6.1.0' 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
 
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v2 
 
    - name: Remove unwanted files 
      run: | 
        rm -rf my_workspaces/.my_workspaces 
        rm -rf README.md 
        rm -rd README_EN.md 
        rm -rf .git 
        rm -rf .github 
 
    - name: Create Release 
      id: create_release 
      uses: actions/create-release@v1 
      env: 
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }} 
      with: 
        tag_name: ${{ env.VERSION }} 
        release_name: UY-Scuti ${{ env.VERSION }} 
        draft: false 
        prerelease: false 
        body: |
          ## 更新内容
          ### 新的功能
          1. 现在 `super` 原始大小选项仅在提取过一次 `super` 后才会显示。
          2. 重构 Rom 包的相关功能已重写，现在在打包 Odin Rom 时会询问是否拥有独立基带分区文件，这两种取决于你的设备。
          3. 7z、boot editor 版本更新
          4. 移除 vbmeta 校验的功能已添加到一键修改。
          5. 简易识别调整，对于三星 Rom，解压后它的逻辑还会保留 `optics.img` 以及 `vbmeta` 相关文件以与一键修改匹配。
          6. 提取所有逻辑变化，仅在仅有 img 存在时才会显示。
          7. 带回解码，编码功能。
          8. apktool 版本更新到2.10.0
          9. 一键修改工具添加了英文翻译支持
          10. Erofs 打包工具更新，打包速度巨大提升，至少20倍，例如原本打包100秒，现在只需5秒

          ## Release Notes
          ### New Features
          1. The `super` original size option now only appears after extracting `super` once.
          2. The ROM package-related functions have been rewritten. When packaging Odin ROM, it will ask if you have a separate baseband partition file, depending on your device.
          3. Updated versions of 7z and boot editor.
          4. The feature to remove vbmeta verification has been added to the one-click modification.
          5. Simplified identification adjustments. For Samsung ROMs, after extraction, the logic will retain `optics.img` and `vbmeta` related files to match the one-click modification.
          6. Extraction logic changes, only showing when only img exists.
          7. Reintroduced decoding and encoding functions.
          8. Updated apktool version to 2.10.0
          9. Added English translation support to the one-click modification tool.
          10. The Erofs packaging tool has been updated, and the packaging speed has been greatly improved, at least 20 times. For example, packaging originally took 100 seconds, but now it only takes 5 seconds.
 
    - name: Archive project 
      run: zip -r UY-Sct_${{ env.VERSION }}.zip . 
 
    - name: Upload Release Asset 
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1 
      env: 
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }} 
      with: 
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./UY-Sct_${{ env.VERSION }}.zip 
        asset_name: UY-Sct_${{ env.VERSION }}.zip 
        asset_content_type: application/zip
