name: Release 
 
on: 
  workflow_dispatch: 
 
env: 
  VERSION: '4.0.0' 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
 
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v2 
 
    - name: Remove unwanted files 
      run: | 
        rm -rf my_workspaces/.my_workspaces 
        rm -rf README.md 
        rm -rd README_EN.md 
        rm -rf .git 
        rm -rf .github 
 
    - name: Create Release 
      id: create_release 
      uses: actions/create-release@v1 
      env: 
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }} 
      with: 
        tag_name: ${{ env.VERSION }} 
        release_name: UY-Scuti ${{ env.VERSION }} 
        draft: false 
        prerelease: false 
        body: |
          ## 更新内容
          ### 新的功能
          1. 现在 `super` 原始大小选项仅在 `super` 大小文件存在时才会显示。
          2. 重构 Rom 包的相关功能已重写，现在在打包 Odin Rom 时会询问是否拥有独立基带分区文件，这两种取决于你的设备。
          3. 7z 版本更新。
          4. 移除 vbmeta 校验的功能已添加到一键修改。
          5. 简易识别调整，对于三星 Rom，解压后它的逻辑还会保留 `optics.img` 以及 `vbmeta` 相关文件以与一键修改匹配。
          
          ## What's New
          ### New Features
          1. The `super` original size option now only appears when `super` size files are present.
          2. Refactored Rom package functionality has been rewritten. When packaging Odin Rom, it will now ask if you have a separate baseband partition file, depending on your device.
          3. Updated 7z version.
          4. The feature to remove `vbmeta` verification has been added to the one-click modification.
          5. Simplified recognition adjustments. For Samsung Rom, after extraction, its logic will retain `optics.img` and `vbmeta` related files to match the one-click modification.
 
    - name: Archive project 
      run: zip -r UY-Sct_${{ env.VERSION }}.zip . 
 
    - name: Upload Release Asset 
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1 
      env: 
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }} 
      with: 
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./UY-Sct_${{ env.VERSION }}.zip 
        asset_name: UY-Sct_${{ env.VERSION }}.zip 
        asset_content_type: application/zip
