name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Remove workflow files
      run: rm -rf .github/workflows/

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: UY-Sct ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Archive project
      run: zip -r UY-Sct-${{ github.ref }}.zip

    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./UY-Sct-${{ github.ref }}.zip
        asset_name: UY-Sct-${{ github.ref }}.zip
        asset_content_type: application/zip
